In [4]:
import pandas as pd
import pdfplumber
# from sqlalchemy import create_engine
pd.set_option("display.max_rows", 6000)

tabulationPath = "Tabulation/"
fileList = ['1', '2', '3', '4']

dfList = []
for file in fileList:
	pdf = pdfplumber.open(tabulationPath + file + '.pdf')
	pages = pdf.pages
	for page in pages:
		table = page.extract_table()
		df = pd.DataFrame(table)
		df.iloc[0, 0] = "RegistrationNum"
# 		df.set_index(0, inplace = True)
		dfList.append(df)

# def semesterSwitcher(s):
#     switch = {
#         "1": "1-1",
#         "2": "1-2",
#         "3": "2-1",
#         "4": "2-2",
#         "5": "3-1",
#         "6": "3-2",
#         "7": "4-1",
#         "8": "4-2"
#     }
#     return switch.get(s[0])

In [5]:
courseNames = dict()
courseNames = {
    'CSE133' : 'Structured Programming Language',
    'CSE134' : 'Structured Programming Language Lab',
    'CSE143' : 'Discrete Mathematics',
    'CSE144' : 'Discrete Mathematics Lab',
    'EEE109D' : 'Electrical Circuits',
    'EEE110D' : 'Electrical Circuits Lab',
    'ENG101D' : 'Effective Communication in English',
    'ENG102D' : 'English Language Lab 1',
    'MAT102D' : 'Matrices, Vector Analysis and Geometry',

    'CSE137' : 'Data Structure',
    'CSE138' : 'Data Structure Lab',
    'EEE111D' : 'Electronic Devices and Circuits',
    'EEE112D' : 'Electronic Devices and Circuits Lab',
    'IPE106D' : 'Engineering Graphics',
    'IPE108D' : 'Workshop Practice',
    'PHY103D' : 'Mechanics, Wave, Heat & Thermodynamics',
    'MAT103D' : 'Calculus',
    'BNG105D' : 'Bangla Language',
    'CSE150' : 'Project Work 1',

    'CSE233' : 'Object Oriented Programming Language',
    'CSE234' : 'Object Oriented Programming Language Lab',
    'CSE237' : 'Algorithm Design & Analysis',
    'CSE238' : 'Algorithm Design & Analysis Lab',
    'BUS203D' : 'Cost and Management Accounting',
    'PHY202D' : 'Basic Physics Lab',
    'PHY207D' : 'Electromagnetism, Optics & Modern Physics',
    'STA202D' : 'Basic Statistics & Probability',

    'CSE239' : 'Numerical Analysis',
    'CSE240' : 'Numerical Analysis Lab',
    'CSE245' : 'Theory of Computation',
    'CSE249' : 'Ethics and Cyber Law',
    'CSE250' : 'Project Work 2',
    'CSE252' : 'Competitive Programming',
    'ECO105D' : 'Principles of Economics',
    'EEE201D' : 'Digital Logic Design',
    'EEE202D' : 'Digital Logic Design Lab',
    'MAT204D' : 'Complex Variables, Laplace Transform and Fourier Series'
}

def getCourse(courseString):
    Course = {
        "CourseID": "",
        "CourseName": "",
        "Semester": "",
        "Credit": 0.00,
        "isMajor": True,
        "isLab": True
    }
    c = courseString.split()
    Course["CourseID"] = c[0]
    Course["CourseName"] = courseNames.get(c[0])
    Course["Semester"] = c[2][0]
    Course["Credit"] = float(c[1])
    code = c[0][3:6]
    Course["isMajor"] = False if (int(code[1]) < 2) else True
    Course["isLab"] = True if (int(code) % 2 == 0) else False    
    return Course

In [6]:
courseList = []
for df in dfList:
    for i in range(3, df.shape[1]):
        s = df.iloc[0, i]
        if((s != None) and (len(s) >= 6) and (s[3].isnumeric())):
            course = getCourse(s)
            if(course not in courseList):
                courseList.append(course)

cdf = pd.DataFrame(courseList)
# cdf.set_index("CourseID", inplace=True)

In [7]:
cdf.shape

(38, 6)

In [8]:
cdf.reset_index(inplace = True)

In [9]:
studentList = []
for df in dfList:
    for i in range(1, df.shape[0]):
        if(df.iloc[i, 0] != None):
            student = dict()
            student["RegistrationNum"] = df.iloc[i, 0]
            student["Session"] = df.iloc[i, 1]
            student["Name"] = df.iloc[i, 2].replace('\n', ' ')
            if(student not in studentList):
                studentList.append(student)
sdf = pd.DataFrame(studentList)
# sdf.set_index("RegistrationNum", inplace = True)
sdf

    RegistrationNum    Session                              Name
0        2016331020  2016-2017                   MD. SADEKUJAMAN
1        2016331039  2016-2017                   MD. RAKIB AHSAN
2        2017331001  2017-2018                   FAHIM UR RASHID
3        2017331003  2017-2018                    TANJIL BHOIYAN
4        2017331005  2017-2018                MD. MARUFUR RAHMAN
5        2017331006  2017-2018                MD. TAMZID HOSSAIN
6        2017331007  2017-2018                        OBHI DATTA
7        2017331008  2017-2018                      ARPITA GHOSH
8        2017331009  2017-2018                     FAHIM AL AMIN
9        2017331010  2017-2018                  M. EBRAHIM SAZIN
10       2017331011  2017-2018           FARINA TAHSIN CHOWDHURY
11       2017331012  2017-2018                     AYESHA AFROZE
12       2017331013  2017-2018               NAVID ISHRIYAQ AMIN
13       2017331014  2017-2018              SYED ASHRAF AL TASIN
14       2017331015  2017-2018                  MOZAMMAL HOSSAIN
15       2017331016  2017-2018                        LAZU ISLAM
16       2017331017  2017-2018           MD. TANVIR RAHMAN TAREQ
17       2017331018  2017-2018               IFTEKHAR AHMED RANA
18       2017331019  2017-2018                   MD. TARIK HASAN
19       2017331020  2017-2018             MD.NAFIUL ISLAM PIASH
20       2017331021  2017-2018                      ABHISHEK DEY
21       2017331022  2017-2018         MD. ASHIKUR RAHMAN BISHAL
22       2017331023  2017-2018                     SANI TALUKDER
23       2017331024  2017-2018                      SHAKIL AHMED
24       2017331025  2017-2018               JAHEDUL ALAM JUNAED
25       2017331026  2017-2018                 MD. FAHIMUL ISLAM
26       2017331027  2017-2018                         AL- MASUM
27       2017331028  2017-2018           SHAHRIAR IBNE SAIFULLAH
28       2017331029  2017-2018             ZAHID KHANDAKER SUMON
29       2017331030  2017-2018                   FARJANA SULTANA
30       2017331031  2017-2018                      NAIMUL HASAN
31       2017331032  2017-2018                     RIM CHOWDHURY
32       2017331033  2017-2018                SAIFUL ISLAM SAGOR
33       2017331034  2017-2018                REYAD HASAN RINKON
34       2017331035  2017-2018  MD. AZHARUL KARIM CHOWDHURY ANIK
35       2017331036  2017-2018                 MD. FUAD AL HASIB
36       2017331037  2017-2018                    SAMAUN HOSSAIN
37       2017331038  2017-2018         ABDULLAH BIN KHALED SHOVO
38       2017331039  2017-2018                      PARTHA GHOSH
39       2017331040  2017-2018                 MD. ASHIKUL ISLAM
40       2017331041  2017-2018                 TRINA CHAKRABORTY
41       2017331042  2017-2018                   MD. OMAR FARUQE
42       2017331043  2017-2018                      MEHEDI HASAN
43       2017331044  2017-2018                       SAMARA PAUL
44       2017331045  2017-2018                 MD TOWSIF HOSSAIN
45       2017331046  2017-2018            SEEMANTA BHATTACHARJEE
46       2017331047  2017-2018         MD. NEYAMUL ISLAM SHIBBIR
47       2017331048  2017-2018                  EJAZ AHMED MIRAJ
48       2017331049  2017-2018                  MD. AKIBUL ISLAM
49       2017331050  2017-2018                 MD. MUHTASIM FUAD
50       2017331051  2017-2018               MD. HASIBUR RAHAMAN
51       2017331052  2017-2018         MD. RAKIBUL HASAN BANDHAN
52       2017331053  2017-2018                   MD. ABDUS SALAM
53       2017331054  2017-2018                     IQRAMUL ISLAM
54       2017331055  2017-2018                       UMME HABIBA
55       2017331056  2017-2018      MD. MAZHARUL ISLAM CHOWDHURY
56       2017331057  2017-2018                       ISHMAM ABID
57       2017331058  2017-2018                     MD. KAEF KHAN
58       2017331059  2017-2018                      NAIMUL HASAN
59       2017331060  2017-2018    MD. BADRUL ALAM SIDDIQUE MASFY
60       2017331061  2017-2018              MD. MASUM ALAM NAHID
61       2017331062  2017-2018                   SUPRODIP SORKAR
62       2017331063  2017-2018                  KIRITI MUKHERJEE
63       2017331064  2017-2018                        JOYDIP DAS
64       2017331065  2017-2018                    MD. ISAHAQ ALI
65       2017331066  2017-2018           MD. TARIKUL ISLAM UTHSO
66       2017331067  2017-2018              SHAH ASHFAQUR RAHMAN
67       2017331068  2017-2018            MD.JAKIR HOSSEN SHAGOR
68       2017331069  2017-2018                     SOHAIYA ISLAM
69       2017331072  2017-2018                   ABDULLAHIL KAFI
70       2017331073  2017-2018                   ARITRA MAZUMDER
71       2017331074  2017-2018                  RAFAT ASHRAF JOY
72       2017331075  2017-2018                MD MUSTAQUR RAHMAN
73       2017331076  2017-2018                        PRITAM DAS
74       2017331078  2017-2018                       AHMAD RAKIB
75       2017331079  2017-2018                 FAYJUL ISLAM RAZA
76       2017331080  2017-2018           NASIF ANWAR KHAN PALLAB
77       2017331081  2017-2018                  MD. KAMRUL ISLAM
78       2017331082  2017-2018               LOKNATH BANIK SAGOR
79       2017331084  2017-2018          SYED JAMIL MAHMOOD EFTEE
80       2017331085  2017-2018              SYED SHARFARAZ AHMED
81       2017331086  2017-2018                MUHID HASSAN RISVY
82       2017331087  2017-2018                  ANIRUDDHA HALDER
83       2017331088  2017-2018                      ROMAN RAIHAN
84       2017331089  2017-2018             MD. SABBIR IRFAN CHY.
85       2017331090  2017-2018                        MD. SHAKIL
86       2017331091  2017-2018                 SUKENTO KUMAR DAS
87       2017331092  2017-2018          S. M. ZUHAYER ANZUM FUAD
88       2017331093  2017-2018                   MAHMUDUR RAHMAN
89       2017331094  2017-2018              MAHMODUL HASAN SAKIB
90       2017331095  2017-2018                       SOURAV SAHA
91       2017331096  2017-2018                SABIHA TAHSIN SOHA
92       2017331097  2017-2018                   ISMAHABUL HASAN
93       2017331098  2017-2018                    SORWAR HUSSAIN
94       2017331099  2017-2018          FAIRUZ RAHAMAN CHOWDHURY
95       2017331100  2017-2018                    ASHIKUR RAHMAN
96       2017331101  2017-2018                  ASIF IDRIS TUHIN
97       2017331102  2017-2018              CHANDRASHEKHAR GHOSH
98       2017331103  2017-2018                     SHADMAN SAKIB
99       2017331104  2017-2018             MD. EMTIAZ KABIR IFTU
100      2017331105  2017-2018                     GOLAM  JILANI
101      2017331106  2017-2018                       PRATO DEWAN
102      2017331107  2017-2018            BISWAS MAHMUDUL HASSAN
103      2017331108  2017-2018                ZESHAN AHMED NABIN
104      2017331109  2017-2018           MD. ZAHIDUL AKRAM RATUL
105      2016331063  2016-2017                      SHAILA AKTER
106      2016331077  2016-2017                 RUHUL.QUDUS.MIRAZ

In [10]:
# ### resultList = []
# rdf = pd.DataFrame(columns=['RegistrationNum', 'CourseID', 'GPA', 'LetterGrade'])
# for df in dfList:
#     row = 1 if df.iloc[1, 0] != None else 2
#     for row in range(row, df.shape[0]):
#         for column in range(3, df.shape[1]):
#             s = df.iloc[0, column]
#             if((s != None) and (len(s) >= 6) and (s[3].isnumeric())):
#                 result = dict()
#                 result["RegistrationNum"] = df.iloc[row, 0]
#                 result["CourseID"] = s.split()[0]
#                 gpaString = df.iloc[row, column]
#                 if gpaString == '':
#                     continue
#                 result["GPA"] = float(gpaString.split()[0])
#                 result["LetterGrade"] = gpaString.split()[1]
# #                 resultList.append(result)
#                 try:
#                     filt = (rdf['RegistrationNum'] == result["RegistrationNum"]) & (rdf['CourseID'] == result["CourseID"])
#                     rdf.drop(index = rdf.loc[filt].index, inplace = True)
#                 except:
#                     co = 0
#                 finally:
# #                     rdf = rdf.append({"RegistrationNum": result["RegistrationNum"], \
# #                                "CourseID" : result["CourseID"], \
# #                                "GPA" : result["GPA"], \
# #                                "LetterGrade" : result["LetterGrade"]}, \
# #                                ignore_index=True)
#                     rdf = rdf.append(result, ignore_index = True)

# # rdf = pd.DataFrame(resultList)
# # rdf.set_index("RegistrationNum", inplace = True)

In [11]:
### resultList = []
rdf = pd.DataFrame(columns=['RegistrationNum', 'CourseID', 'CourseName', 'Semester', 'Credit', 'isMajor', 'isLab', 'GPA', 'LetterGrade'])
for df in dfList:
    row = 1 if df.iloc[1, 0] != None else 2
    for row in range(row, df.shape[0]):
        for column in range(3, df.shape[1]):
            s = df.iloc[0, column]
            if((s != None) and (len(s) >= 6) and (s[3].isnumeric())):
                result = dict()
                result["RegistrationNum"] = df.iloc[row, 0]
                
                course = getCourse(s)
                result["CourseID"] = course['CourseID']
                result["CourseName"] = course['CourseName']
                result["Semester"] = course['Semester']
                result["Credit"] = course['Credit']
                result["isMajor"] = course['isMajor']
                result["isLab"] = course['isLab']
                
                gpaString = df.iloc[row, column]
                if gpaString == '':
                    continue
                result["GPA"] = float(gpaString.split()[0])
                result["LetterGrade"] = gpaString.split()[1]
#                 resultList.append(result)
                try:
                    filt = (rdf['RegistrationNum'] == result["RegistrationNum"]) & (rdf['CourseID'] == result["CourseID"])
                    rdf.drop(index = rdf.loc[filt].index, inplace = True)
                except:
                    co = 0
                finally:
                    rdf = rdf.append(result, ignore_index = True)

# rdf = pd.DataFrame(resultList)
# rdf.set_index("RegistrationNum", inplace = True)

In [12]:
rdf.loc[rdf["RegistrationNum"] == '2016331020']

,RegistrationNum,CourseID,CourseName,Semester,Credit,isMajor,isLab,GPA,LetterGrade
0,2016331020,CSE133,Structured Programming Language,1,3.0,True,False,2.75,B-
1,2016331020,CSE134,Structured Programming Language Lab,1,2.0,True,True,4.00,A+
2,2016331020,CSE143,Discrete Mathematics,1,3.0,True,False,4.00,A+
3,2016331020,CSE144,Discrete Mathematics Lab,1,1.0,True,True,3.75,A
4,2016331020,EEE109D,Electrical Circuits,1,3.0,False,False,3.75,A
5,2016331020,EEE110D,Electrical Circuits Lab,1,1.5,False,True,3.50,A-
6,2016331020,ENG101D,Effective Communication in English,1,2.0,False,False,3.00,B
7,2016331020,ENG102D,English Language Lab 1,1,1.0,False,True,3.25,B+
8,2016331020,MAT102D,"Matrices, Vector Analysis and Geometry",1,3.0,False,True,2.00,C-
827,2016331020,BNG105D,Bangla Language,2,3.0,False,False,2.75,B-
828,2016331020,CSE137,Data Structure,2,3.0,True,False,3.50,A-
829,2016331020,CSE138,Data Structure Lab,2,2.0,True,True,4.00,A+
830,2016331020,CSE150,Project Work 1,2,1.0,True,True,4.00,A+
831,2016331020,EEE111D,Electronic Devices and Circuits,2,3.0,False,False,4.00,A+
832,2016331020,EEE112D,Electronic Devices and Circuits Lab,2,1.5,False,True,2.25,C
833,2016331020,IPE106D,Engineering Graphics,2,1.5,False,True,4.00,A+
834,2016331020,IPE108D,Workshop Practice,2,1.0,False,True,3.50,A-
835,2016331020,MAT103D,Calculus,2,3.0,False,False,3.50,A-
1673,2016331020,PHY103D,"Mechanics, Wave, Heat & Thermodynamics",2,3.0,False,False,3.50,A-
1761,2016331020,BUS203D,Cost and Management Accounting,3,3.0,False,False,3.25,B+
1762,2016331020,CSE233,Object Oriented Programming Language,3,3.0,True,False,4.00,A+
1763,2016331020,CSE234,Object Oriented Programming Language Lab,3,2.0,True,True,4.00,A+
1764,2016331020,CSE237,Algorithm Design & Analysis,3,3.0,True,False,3.50,A-
1765,2016331020,CSE238,Algorithm Design & Analysis Lab,3,2.0,True,True,4.00,A+
2351,2016331020,PHY202D,Basic Physics Lab,3,1.5,False,True,3.75,A
2352,2016331020,PHY207D,"Electromagnetism, Optics & Modern Physics",3,3.0,False,False,3.00,B
2353,2016331020,STA202D,Basic Statistics & Probability,3,3.0,False,True,3.25,B+
2688,2016331020,CSE239,Numerical Analysis,4,2.0,True,False,3.50,A-
2689,2016331020,CSE240,Numerical Analysis Lab,4,1.5,True,True,4.00,A+
2690,2016331020,CSE245,Theory of Computation,4,2.0,True,False,4.00,A+
2691,2016331020,CSE249,Ethics and Cyber Law,4,2.0,True,False,2.50,C+
2692,2016331020,CSE250,Project Work 2,4,1.0,True,True,0.00,F
2693,2016331020,CSE252,Competitive Programming,4,1.5,True,True,4.00,A+
2694,2016331020,ECO105D,Principles of Economics,4,3.0,False,False,3.50,A-
3459,2016331020,EEE201D,Digital Logic Design,4,3.0,False,False,2.75,B-
3460,2016331020,EEE202D,Digital Logic Design Lab,4,2.0,False,True,3.25,B+
3461,2016331020,MAT204D,"Complex Variables, Laplace Transform and Fouri...",4,3.0,False,True,3.50,A-

In [13]:
rdf.shape

(3803, 9)

import sqlite3
connection = sqlite3.connect("dbb.sqlite3")
cursor = connection.cursor()

# populating the details_student table

for row in range(sdf.shape[0]):
    record = sdf.iloc[row]
    cursor.execute("INSERT INTO details_student VALUES (?, ?, ?);",
                  (record['RegistrationNum'], record['Session'], record['Name'])
                  )
connection.commit()

# populating the details_result table
for row in range(rdf.shape[0]):
    record = rdf.iloc[row]
    cursor.execute("INSERT INTO details_result (courseId, courseName, semester, credit, isMajor, isLab, gpa, stuId_id) \
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?);", (record["CourseID"], record["CourseName"], record["Semester"], record["Credit"], record["isMajor"], record["isLab"], record["GPA"], record["RegistrationNum"]))
connection.commit()

UPDATE details_result SET isLab = 0 WHERE courseId = 'MAT102D';
UPDATE details_result SET isLab = 0 WHERE courseId = 'MAT204D';
UPDATE details_result SET isLab = 0 WHERE courseId = 'STA202D';

CREATE TRIGGER update_credit_and_cgpa
BEFORE INSERT ON details_result
BEGIN

In [78]:
import sqlite3
connection = sqlite3.connect("bd.sqlite3")
cursor = connection.cursor()


for row in range(sdf.shape[0]):
    reg = sdf.iloc[row, 0]
    print('working for ', reg)
    result = rdf.loc[rdf['RegistrationNum'] == reg]
    completedCredits = 0
    cgpa = 0.0
    numerator = 0.0
    denominator = 0.0
    for record in range(result.shape[0]):
        if(result.iloc[record, 7] > 0.0):
            numerator += result.iloc[record, 4] * result.iloc[record, 7]
            denominator += result.iloc[record, 4]
    completedCredits = denominator
    cgpa = round(float(numerator/denominator), 2)
    print(reg, ' has completed ', completedCredits, 'has a cgpa of', cgpa)
    cursor.execute("UPDATE details_student SET credits = ?, cgpa = ? WHERE reg = ?;", \
                   (completedCredits, cgpa, reg))
#     cursor.execute("UPDATE details_student SET credits = 80.0, SET cgpa = 3.5 WHERE reg = ?;", \
#                    (reg))
connection.commit()

working for  2016331020
2016331020  has completed  82.0 has a cgpa of 3.42
working for  2016331039
2016331039  has completed  80.0 has a cgpa of 3.19
working for  2017331001
2017331001  has completed  80.0 has a cgpa of 2.95
working for  2017331003
2017331003  has completed  38.0 has a cgpa of 2.5
working for  2017331005
2017331005  has completed  71.0 has a cgpa of 2.71
working for  2017331006
2017331006  has completed  83.0 has a cgpa of 3.9
working for  2017331007
2017331007  has completed  35.5 has a cgpa of 2.51
working for  2017331008
2017331008  has completed  83.0 has a cgpa of 3.7
working for  2017331009
2017331009  has completed  30.0 has a cgpa of 2.58
working for  2017331010
2017331010  has completed  67.0 has a cgpa of 2.93
working for  2017331011
2017331011  has completed  81.0 has a cgpa of 3.32
working for  2017331012
2017331012  has completed  83.0 has a cgpa of 3.59
working for  2017331013
2017331013  has completed  79.0 has a cgpa of 2.88
working for  2017331014
2017331014  has completed  83.0 has a cgpa of 3.81
working for  2017331015
2017331015  has completed  78.0 has a cgpa of 3.36
working for  2017331016
2017331016  has completed  76.0 has a cgpa of 2.81
working for  2017331017
2017331017  has completed  81.0 has a cgpa of 3.59
working for  2017331018
2017331018  has completed  5.5 has a cgpa of 2.45
working for  2017331019
2017331019  has completed  83.0 has a cgpa of 3.56
working for  2017331020
2017331020  has completed  62.0 has a cgpa of 2.96
working for  2017331021
2017331021  has completed  75.0 has a cgpa of 3.2
working for  2017331022
2017331022  has completed  80.0 has a cgpa of 3.51
working for  2017331023
2017331023  has completed  80.0 has a cgpa of 3.35
working for  2017331024
2017331024  has completed  75.0 has a cgpa of 2.99
working for  2017331025
2017331025  has completed  83.0 has a cgpa of 3.59
working for  2017331026
2017331026  has completed  83.0 has a cgpa of 3.81
working for  2017331027
2017331027  has completed  79.0 has a cgpa of 3.23
working for  2017331028
2017331028  has completed  83.0 has a cgpa of 3.51
working for  2017331029
2017331029  has completed  80.0 has a cgpa of 3.46
working for  2017331030
2017331030  has completed  83.0 has a cgpa of 3.77
working for  2017331031
2017331031  has completed  80.0 has a cgpa of 3.32
working for  2017331032
2017331032  has completed  83.0 has a cgpa of 3.39
working for  2017331033
2017331033  has completed  83.0 has a cgpa of 3.25
working for  2017331034
2017331034  has completed  75.0 has a cgpa of 3.09
working for  2017331035
2017331035  has completed  2.5 has a cgpa of 4.0
working for  2017331036
2017331036  has completed  75.0 has a cgpa of 2.83
working for  2017331037
2017331037  has completed  71.5 has a cgpa of 2.71
working for  2017331038
2017331038  has completed  69.5 has a cgpa of 2.83
working for  2017331039
2017331039  has completed  73.0 has a cgpa of 3.04
working for  2017331040
2017331040  has completed  83.0 has a cgpa of 3.42
working for  2017331041
2017331041  has completed  83.0 has a cgpa of 3.68
working for  2017331042
2017331042  has completed  78.0 has a cgpa of 3.2
working for  2017331043
2017331043  has completed  68.0 has a cgpa of 3.01
working for  2017331044
2017331044  has completed  83.0 has a cgpa of 3.66
working for  2017331045
2017331045  has completed  81.0 has a cgpa of 3.06
working for  2017331046
2017331046  has completed  83.0 has a cgpa of 3.49
working for  2017331047
2017331047  has completed  77.0 has a cgpa of 3.52
working for  2017331048
2017331048  has completed  79.0 has a cgpa of 3.23
working for  2017331049
2017331049  has completed  80.0 has a cgpa of 3.44
working for  2017331050
2017331050  has completed  83.0 has a cgpa of 3.63
working for  2017331051
2017331051  has completed  83.0 has a cgpa of 3.54
working for  2017331052
2017331052  has completed  48.5 has a cgpa of 2.5
working for  2017331053
2017331053  has completed  50.0 has a cgpa of 2.75
working for  2017331054
2017331054  has completed  77.0 has a cgpa of 3.57
working for  2017331055
2017331055  has completed  83.0 has a cgpa of 3.02
working for  2017331056
2017331056  has completed  83.0 has a cgpa of 2.87
working for  2017331057
2017331057  has completed  83.0 has a cgpa of 3.31
working for  2017331058
2017331058  has completed  79.0 has a cgpa of 2.86
working for  2017331059
2017331059  has completed  80.0 has a cgpa of 3.48
working for  2017331060
2017331060  has completed  80.0 has a cgpa of 3.3
working for  2017331061
2017331061  has completed  78.0 has a cgpa of 3.25
working for  2017331062
2017331062  has completed  77.0 has a cgpa of 2.99
working for  2017331063
2017331063  has completed  83.0 has a cgpa of 3.77
working for  2017331064
2017331064  has completed  83.0 has a cgpa of 3.46
working for  2017331065
2017331065  has completed  84.0 has a cgpa of 3.25
working for  2017331066
2017331066  has completed  83.0 has a cgpa of 2.98
working for  2017331067
2017331067  has completed  58.5 has a cgpa of 2.7
working for  2017331068
2017331068  has completed  77.0 has a cgpa of 3.01
working for  2017331069
2017331069  has completed  83.0 has a cgpa of 3.33
working for  2017331072
2017331072  has completed  81.0 has a cgpa of 3.39
working for  2017331073
2017331073  has completed  80.0 has a cgpa of 3.39
working for  2017331074
2017331074  has completed  83.0 has a cgpa of 3.48
working for  2017331075
2017331075  has completed  67.0 has a cgpa of 2.93
working for  2017331076
2017331076  has completed  82.0 has a cgpa of 3.23
working for  2017331078
2017331078  has completed  83.0 has a cgpa of 3.32
working for  2017331079
2017331079  has completed  79.0 has a cgpa of 3.28
working for  2017331080
2017331080  has completed  77.5 has a cgpa of 3.48
working for  2017331081
2017331081  has completed  79.0 has a cgpa of 3.21
working for  2017331082
2017331082  has completed  65.0 has a cgpa of 2.86
working for  2017331084
2017331084  has completed  74.5 has a cgpa of 2.86
working for  2017331085
2017331085  has completed  63.5 has a cgpa of 2.94
working for  2017331086
2017331086  has completed  83.0 has a cgpa of 3.29
working for  2017331087
2017331087  has completed  71.0 has a cgpa of 3.01
working for  2017331088
2017331088  has completed  80.0 has a cgpa of 3.36
working for  2017331089
2017331089  has completed  83.0 has a cgpa of 3.34
working for  2017331090
2017331090  has completed  5.5 has a cgpa of 2.48
working for  2017331091
2017331091  has completed  83.0 has a cgpa of 3.41
working for  2017331092
2017331092  has completed  79.5 has a cgpa of 3.15
working for  2017331093
2017331093  has completed  83.0 has a cgpa of 3.16
working for  2017331094
2017331094  has completed  59.0 has a cgpa of 2.77
working for  2017331095
2017331095  has completed  83.0 has a cgpa of 3.7
working for  2017331096
2017331096  has completed  83.0 has a cgpa of 3.43
working for  2017331097
2017331097  has completed  69.0 has a cgpa of 2.74
working for  2017331098
2017331098  has completed  68.0 has a cgpa of 2.93
working for  2017331099
2017331099  has completed  81.0 has a cgpa of 3.0
working for  2017331100
2017331100  has completed  27.5 has a cgpa of 2.68
working for  2017331101
2017331101  has completed  83.0 has a cgpa of 3.4
working for  2017331102
2017331102  has completed  80.0 has a cgpa of 3.09
working for  2017331103
2017331103  has completed  33.5 has a cgpa of 2.84
working for  2017331104
2017331104  has completed  79.0 has a cgpa of 3.23
working for  2017331105
2017331105  has completed  80.0 has a cgpa of 3.3
working for  2017331106
2017331106  has completed  83.0 has a cgpa of 3.43
working for  2017331107
2017331107  has completed  80.0 has a cgpa of 2.97
working for  2017331108
2017331108  has completed  83.0 has a cgpa of 3.09
working for  2017331109
2017331109  has completed  83.0 has a cgpa of 2.97
working for  2016331063
2016331063  has completed  42.0 has a cgpa of 2.41
working for  2016331077
2016331077  has completed  9.5 has a cgpa of 2.86

(10, 9)